config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'home#index', as: 'intranet', via: :all
  scope path: 'snowflake' do
    get '/get_roles', to: 'uploads#get_roles'
    get '/get_track_categories', to: 'uploads#get_track_categories'
    get '/get_tracks', to: 'uploads#get_tracks'
    resources :uploads, :roles, :track_categories, :tracks, :levels
    resources :cycles do
      resources :assessment_results
    end
    scope module: 'api' do
      namespace :v1 do
        resources :users
        get '/get_static_data', to: 'users#get_static_data'
        post '/create_assessment', to: 'users#create_assessment'
        get '/get_assessment', to: 'users#get_assessment'
        post '/update_assessment', to: 'users#update_assessment'
      end
    end
    root 'users#new'
  end
end

app/models/cycle.rb
class Cycle

  include Mongoid::Document
  include Mongoid::Timestamps

  field :emp_duration_start,     type: Date
  field :emp_duration_end,       type: Date
  field :manager_duration_start, type: Date
  field :manager_duration_end,   type: Date
  field :is_open,                type: Boolean

  has_many :assessment_results

  validates :emp_duration_start, :emp_duration_end, 
   :manager_duration_start, :manager_duration_end, :is_open, presence: true
end

app/controllers/cycles_controller.rb
class CyclesController < ApplicationController
  #It is assumed that only one cycle will be open at a time
  def index
    @cycles = Cycle.all
  end

  def new
    @cycle = Cycle.new
  end

  def edit
    @cycle = Cycle.find(params[:id])
  end

  def create
    @cycle = Cycle.new(cycle_params)

    if @cycle.save
      redirect_to cycles_path
    else
      render 'new'
    end
  end

  def update
    @cycle = Cycle.find(params[:id])

    if @cycle.update(cycle_params)
      redirect_to cycles_path
    else
      render 'new'
    end
  end

  def destroy
    @cycle = Cycle.find(params[:id])
    @cycle.destroy

    redirect_to cycles_path
  end

  private
    def cycle_params
      params.require(:cycle).permit(
        :emp_duration_start,
        :emp_duration_end,
        :manager_duration_start,
        :manager_duration_end,
        :is_open
      )
    end
end

app/helpers/cycles_helper.rb
module CyclesHelper
end

app/views/cycles/_form.html.haml
= simple_form_for @cycle do |f|
  = f.input :emp_duration_start, as: :date, html5: true
  = f.input :emp_duration_end, as: :date, html5: true
  = f.input :manager_duration_start, as: :date, html5: true
  = f.input :manager_duration_end, as: :date, html5: true
  = f.input :is_open, as: :radio_buttons
  = f.button :submit, 'Save', class: 'btn btn-sm btn-success'
  = link_to 'Back', cycles_path, class: 'btn btn-sm btn-default'

app/views/cycles/edit.html.haml
%h3 Edit a cycle
= render 'form'

app/views/cycles/index.html.haml
.row.mb-3.mt-5
  .col-7
    %h3 Listing Cycles
  .col-5
    = link_to 'Add new cycle', new_cycle_path, class: 'btn btn-primary btn-md'
  
%table#cyclesTable.display.table.table-bordered.table-hover
  %thead
    %tr
      %th Employee assessment starts at
      %th Employee assessment ends at
      %th Manager assessment starts at
      %th Manager assessment ends at
      %th Is open?
      %th Actions
  %tbody
    - @cycles.each do |cycle|
      %tr
        %td= cycle.emp_duration_start
        %td= cycle.emp_duration_end
        %td= cycle.manager_duration_start
        %td= cycle.manager_duration_end
        %td= cycle.is_open ? 'Yes' : 'No'
        %td
          = link_to 'Edit', edit_cycle_path(cycle), class: 'btn btn-info btn-sm'
          = link_to 'Destroy', cycle_path(cycle), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'
          = link_to 'Assessments', cycle_assessment_results_path(cycle), class: 'btn btn-info btn-sm'

app/views/cycles/new.html.haml
%h3 Create a cycle
= render 'form'