config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'home#index', as: 'intranet', via: :all
  scope path: 'snowflake' do
    get '/get_roles', to: 'uploads#get_roles'
    get '/get_track_categories', to: 'uploads#get_track_categories'
    get '/get_tracks', to: 'uploads#get_tracks'
    resources :uploads, :roles, :track_categories, :tracks, :levels
    resources :cycles do
      resources :assessment_results
    end
    scope module: 'api' do
      namespace :v1 do
        resources :users
        get '/get_static_data', to: 'users#get_static_data'
        post '/create_assessment', to: 'users#create_assessment'
        get '/get_assessment', to: 'users#get_assessment'
        post '/update_assessment', to: 'users#update_assessment'
      end
    end
    root 'users#new'
  end
end

app/models/role.rb
class Role
  
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name, type: String
  field :can_assess, type: String

  has_many :users
  has_many :track_categories

  validates :name, presence: true, uniqueness: true
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
	def index
		@roles = Role.all
	end

	def show
	end

	def edit
		@role = Role.find(params[:id])
	end

	def update
		role = Role.find(params[:id])
 
  	if role.update(role_params)
    	redirect_to roles_path
  	else
    	render 'edit'
  	end
	end

	def destroy
		role = Role.find(params[:id])
  	role.destroy

  	redirect_to roles_path
	end

	private
		def role_params
			params.require(:role).permit(:name, can_assess: [])
		end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.haml
= simple_form_for @role do |f|
  = f.input :name
  = f.input :can_assess, as: :array
  = f.button :submit, 'Save', class: 'btn btn-sm btn-success'
  = link_to 'Back', roles_path, class: 'btn btn-sm btn-default'

app/views/roles/edit.html.haml
%h3 Edit a role
= render 'form'

app/views/roles/index.html.haml
.row.mb-3.mt-5
  %h3 Listing Roles
  
%table#rolesTable.display.table.table-bordered.table-hover
  %thead
    %tr
      %th Name
      %th Can assess
      %th Actions
  %tbody
    - @roles.each do |role|
      %tr
        %td= role.name
        %td= role.can_assess
        %td
          = link_to 'Edit', edit_role_path(role), class: 'btn btn-info btn-sm'
          = link_to 'Destroy', role_path(role), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'