config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'home#index', as: 'intranet', via: :all
  scope path: 'snowflake' do
    get '/get_roles', to: 'uploads#get_roles'
    get '/get_track_categories', to: 'uploads#get_track_categories'
    get '/get_tracks', to: 'uploads#get_tracks'
    resources :uploads, :roles, :track_categories, :tracks, :levels
    resources :cycles do
      resources :assessment_results
    end
    scope module: 'api' do
      namespace :v1 do
        resources :users
        get '/get_static_data', to: 'users#get_static_data'
        post '/create_assessment', to: 'users#create_assessment'
        get '/get_assessment', to: 'users#get_assessment'
        post '/update_assessment', to: 'users#update_assessment'
      end
    end
    root 'users#new'
  end
end

app/models/level.rb
class Level

  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :seq_no, type: Integer
  field :description, type: String
  field :example_behaviour, type: Array
  field :example_task, type: Array

  belongs_to :track

  validates :seq_no, presence: true
  validates :seq_no, uniqueness: { scope: [:role, :track_category, :track] }
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
	def index
		@levels = Level.all
	end

	def edit
		@level = Level.find(params[:id])
	end

	def update
		level = Level.find(params[:id])

		if level.update(level_params)
    	redirect_to levels_path
  	else
    	render 'edit'
    end
	end

	def destroy
		level = Level.find(params[:id])
		level.destroy

		redirect_to levels_path
	end

	private
		def level_params
			params.require(:level).permit(
				:seq_no,
				:description,
				example_behaviour: [],
				example_task: []
			)
		end
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/views/levels/_form.html.haml
= simple_form_for @level do |f|
  = f.input :seq_no
  = f.input :description
  = f.input :example_behaviour, as: :array
  = f.input :example_task, as: :array
  = f.button :submit, 'Save', class: 'btn btn-sm btn-success'
  = link_to 'Back', levels_path, class: 'btn btn-sm btn-default'

app/views/levels/edit.html.haml
%h3 Edit a level
= render 'form'

app/views/levels/index.html.haml
.row.mb-3.mt-5
  %h3 Listing Levels
  
%table#levelsTable.display.table.table-bordered.table-hover
  %thead
    %tr
      %th Seq. no.
      %th Description
      %th Track
      %th Track category
      %th Role
      %th Actions
  %tbody
    - @levels.each do |level|
      %tr
        %td= level.seq_no
        %td= level.description
        %td= level.track.name
        %td= level.track.track_category.name
        %td= level.track.track_category.role.name
        %td
          = link_to 'Edit', edit_level_path(level), class: 'btn btn-info btn-sm'
          = link_to 'Destroy', level_path(level), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'