config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'home#index', as: 'intranet', via: :all
  scope path: 'snowflake' do
    get '/get_roles', to: 'uploads#get_roles'
    get '/get_track_categories', to: 'uploads#get_track_categories'
    get '/get_tracks', to: 'uploads#get_tracks'
    resources :uploads, :roles, :track_categories, :tracks, :levels
    resources :cycles do
      resources :assessment_results
    end
    scope module: 'api' do
      namespace :v1 do
        resources :users
        get '/get_static_data', to: 'users#get_static_data'
        post '/create_assessment', to: 'users#create_assessment'
        get '/get_assessment', to: 'users#get_assessment'
        post '/update_assessment', to: 'users#update_assessment'
      end
    end
    root 'users#new'
  end
end

app/models/assessment_result.rb
class AssessmentResult

  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :total_points, type: Integer
  field :current_level, type: Float
  field :points_to_next_level,  type: Integer
  
  has_many :level_assessments
  belongs_to :cycle
  belongs_to :user

  validates :total_points, :current_level, :points_to_next_level, presence: true
end

app/models/cycle.rb
class Cycle

  include Mongoid::Document
  include Mongoid::Timestamps

  field :emp_duration_start,     type: Date
  field :emp_duration_end,       type: Date
  field :manager_duration_start, type: Date
  field :manager_duration_end,   type: Date
  field :is_open,                type: Boolean

  has_many :assessment_results

  validates :emp_duration_start, :emp_duration_end, 
   :manager_duration_start, :manager_duration_end, :is_open, presence: true
end

app/models/level.rb
class Level

  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :seq_no, type: Integer
  field :description, type: String
  field :example_behaviour, type: Array
  field :example_task, type: Array

  belongs_to :track

  validates :seq_no, presence: true
  validates :seq_no, uniqueness: { scope: [:role, :track_category, :track] }
end

app/models/level_assessment.rb
class LevelAssessment
  
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :user_id,           type: Integer
  field :role_id,           type: Integer
  field :track_id,          type: Integer
  field :level_id,          type: Integer
  field :cycle_id,          type: Integer
  field :updated_by,        type: String
  field :Comments,          type: String
  field :track_category_id, type: Integer

  belongs_to :assessment_result

  validates :user_id, :role_id, :track_category_id,
   :track_id, :level_id, presence: true
end

app/models/role.rb
class Role
  
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name, type: String
  field :can_assess, type: String

  has_many :users
  has_many :track_categories

  validates :name, presence: true, uniqueness: true
end

app/models/track.rb
class Track
  
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name, type: String
  field :description, type: String

  has_many :levels
  belongs_to :track_category

  validates :name, presence: true
  validates :name, uniqueness: { scope: [:role, :track_category] }
end

app/models/track_category.rb
class TrackCategory
  
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name, type: String
  field :description, type: String

  has_many :tracks
  belongs_to :role

  validates :name, presence: true
  validates :name, uniqueness: { scope: :role }
end

app/models/upload.rb
class Upload
  
  include Mongoid::Document
  include Mongoid::Timestamps

  field :type_of_file, type: String
  mount_uploader :input_file, ModelDataUploader
  mount_uploader :csv_report, ReportUploader

  belongs_to :role, optional: true
  belongs_to :track_category, optional: true
  belongs_to :track, optional: true

  validates :type_of_file, presence: true
  validates :input_file,   presence: true
  
  validates :role, presence: true, if: :file_type_track_categories?
  validates :role, :track_category, presence: true, if: :file_type_tracks?
  validates :role, :track_category, :track, presence: true,
   if: :file_type_levels?

  def file_type_track_categories?
    type_of_file == 'Track Categories'
  end

  def file_type_tracks?
    type_of_file == 'Tracks'
  end

  def file_type_levels?
    type_of_file == 'Levels'
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :email, type: String
  field :password, type: String
  field :role, type: String, default: 'Employee'

  has_many :assessment_results

end

app/controllers/cycles_controller.rb
class CyclesController < ApplicationController
  #It is assumed that only one cycle will be open at a time
  def index
    @cycles = Cycle.all
  end

  def new
    @cycle = Cycle.new
  end

  def edit
    @cycle = Cycle.find(params[:id])
  end

  def create
    @cycle = Cycle.new(cycle_params)

    if @cycle.save
      redirect_to cycles_path
    else
      render 'new'
    end
  end

  def update
    @cycle = Cycle.find(params[:id])

    if @cycle.update(cycle_params)
      redirect_to cycles_path
    else
      render 'new'
    end
  end

  def destroy
    @cycle = Cycle.find(params[:id])
    @cycle.destroy

    redirect_to cycles_path
  end

  private
    def cycle_params
      params.require(:cycle).permit(
        :emp_duration_start,
        :emp_duration_end,
        :manager_duration_start,
        :manager_duration_end,
        :is_open
      )
    end
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
	def index
		@levels = Level.all
	end

	def edit
		@level = Level.find(params[:id])
	end

	def update
		level = Level.find(params[:id])

		if level.update(level_params)
    	redirect_to levels_path
  	else
    	render 'edit'
    end
	end

	def destroy
		level = Level.find(params[:id])
		level.destroy

		redirect_to levels_path
	end

	private
		def level_params
			params.require(:level).permit(
				:seq_no,
				:description,
				example_behaviour: [],
				example_task: []
			)
		end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
	def index
		@roles = Role.all
	end

	def show
	end

	def edit
		@role = Role.find(params[:id])
	end

	def update
		role = Role.find(params[:id])
 
  	if role.update(role_params)
    	redirect_to roles_path
  	else
    	render 'edit'
  	end
	end

	def destroy
		role = Role.find(params[:id])
  	role.destroy

  	redirect_to roles_path
	end

	private
		def role_params
			params.require(:role).permit(:name, can_assess: [])
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.find(request.headers[:HTTP_AUTHORIZATION])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cycles_helper.rb
module CyclesHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default.navbar-static-top{:role => "navigation", :style => "margin-bottom: 0"}
  .navbar-header
    %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand Admin Panel
  %ul.nav.navbar-top-links.navbar-right.pull-right
    %li
      = link_to '<i class="fa fa-arrow-left fa-fw"></i>Back to Intranet</a>'.html_safe, intranet_path
  .navbar-default.sidebar{:role => "navigation"}
    .sidebar-nav.navbar-collapse
      %ul#side-menu.nav.in
        %li
          %a{:href => "/"}
            %i.fa.fa-dashboard.fa-fw
            Dashboard
        %li
          = link_to '<i class="fa fa-database fa-fw"></i> Roles</a>'.html_safe, roles_path
        %li
          = link_to '<i class="fa fa-database fa-fw"></i> Track categories</a>'.html_safe, track_categories_path
        %li
          = link_to '<i class="fa fa-database fa-fw"></i> Tracks</a>'.html_safe, tracks_path
        %li
          = link_to '<i class="fa fa-database fa-fw"></i> Levels</a>'.html_safe, levels_path
        %li
          = link_to '<i class="fa fa-database fa-fw"></i> Files</a>'.html_safe, uploads_path
        %li
          = link_to '<i class="fa fa-file fa-fw"></i> Import a file</a>'.html_safe, new_upload_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title
      = content_for?(:title) ? yield(:title) : "Snowflake"
    %meta{:content => "#{content_for?(:description) ? yield(:description) : "Admin Panel"}", :name => "description"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - unless flash.empty?
      %script
        - flash.each do |f|
          - type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info')
          toastr['#{type}']('#{f[1]}');
    #wrapper
      = render 'layouts/navbar'
    #page-wrapper
      %div
        .panel-body
          = yield